/*
 * This file is generated by jOOQ.
*/
package Galaktyka2.tables.pojos;


import Galaktyka2.tables.interfaces.IPlaneta;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Planeta implements IPlaneta {

    private static final long serialVersionUID = 1427800956;

    private String nazwa;
    private String uklad;
    private String masa;
    private String okresOrbitalny;

    public Planeta() {}

    public Planeta(Planeta value) {
        this.nazwa = value.nazwa;
        this.uklad = value.uklad;
        this.masa = value.masa;
        this.okresOrbitalny = value.okresOrbitalny;
    }

    public Planeta(
        String nazwa,
        String uklad,
        String masa,
        String okresOrbitalny
    ) {
        this.nazwa = nazwa;
        this.uklad = uklad;
        this.masa = masa;
        this.okresOrbitalny = okresOrbitalny;
    }

    @Size(max = 100)
    @Override
    public String getNazwa() {
        return this.nazwa;
    }

    @Override
    public Planeta setNazwa(String nazwa) {
        this.nazwa = nazwa;
        return this;
    }

    @Size(max = 100)
    @Override
    public String getUklad() {
        return this.uklad;
    }

    @Override
    public Planeta setUklad(String uklad) {
        this.uklad = uklad;
        return this;
    }

    @Size(max = 100)
    @Override
    public String getMasa() {
        return this.masa;
    }

    @Override
    public Planeta setMasa(String masa) {
        this.masa = masa;
        return this;
    }

    @Size(max = 100)
    @Override
    public String getOkresOrbitalny() {
        return this.okresOrbitalny;
    }

    @Override
    public Planeta setOkresOrbitalny(String okresOrbitalny) {
        this.okresOrbitalny = okresOrbitalny;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Planeta (");

        sb.append(nazwa);
        sb.append(", ").append(uklad);
        sb.append(", ").append(masa);
        sb.append(", ").append(okresOrbitalny);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IPlaneta from) {
        setNazwa(from.getNazwa());
        setUklad(from.getUklad());
        setMasa(from.getMasa());
        setOkresOrbitalny(from.getOkresOrbitalny());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IPlaneta> E into(E into) {
        into.from(this);
        return into;
    }
}
