/*
 * This file is generated by jOOQ.
*/
package Galaktyka2.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IPlaneta extends Serializable {

    /**
     * Setter for <code>public.planeta.nazwa</code>.
     */
    public IPlaneta setNazwa(String value);

    /**
     * Getter for <code>public.planeta.nazwa</code>.
     */
    @Size(max = 100)
    public String getNazwa();

    /**
     * Setter for <code>public.planeta.uklad</code>.
     */
    public IPlaneta setUklad(String value);

    /**
     * Getter for <code>public.planeta.uklad</code>.
     */
    @Size(max = 100)
    public String getUklad();

    /**
     * Setter for <code>public.planeta.masa</code>.
     */
    public IPlaneta setMasa(String value);

    /**
     * Getter for <code>public.planeta.masa</code>.
     */
    @Size(max = 100)
    public String getMasa();

    /**
     * Setter for <code>public.planeta.okres_orbitalny</code>.
     */
    public IPlaneta setOkresOrbitalny(String value);

    /**
     * Getter for <code>public.planeta.okres_orbitalny</code>.
     */
    @Size(max = 100)
    public String getOkresOrbitalny();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IPlaneta
     */
    public void from(Galaktyka2.tables.interfaces.IPlaneta from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IPlaneta
     */
    public <E extends Galaktyka2.tables.interfaces.IPlaneta> E into(E into);
}
