/*
 * This file is generated by jOOQ.
*/
package Galaktyka2.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUklad extends Serializable {

    /**
     * Setter for <code>public.uklad.nazwa</code>.
     */
    public IUklad setNazwa(String value);

    /**
     * Getter for <code>public.uklad.nazwa</code>.
     */
    @Size(max = 100)
    public String getNazwa();

    /**
     * Setter for <code>public.uklad.ilosc_planet</code>.
     */
    public IUklad setIloscPlanet(Integer value);

    /**
     * Getter for <code>public.uklad.ilosc_planet</code>.
     */
    public Integer getIloscPlanet();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUklad
     */
    public void from(Galaktyka2.tables.interfaces.IUklad from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUklad
     */
    public <E extends Galaktyka2.tables.interfaces.IUklad> E into(E into);
}
