/*
 * This file is generated by jOOQ.
*/
package Galaktyka2.tables;


import Galaktyka2.Public;
import Galaktyka2.tables.records.UkladRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Uklad extends TableImpl<UkladRecord> {

    private static final long serialVersionUID = 1664563723;

    /**
     * The reference instance of <code>public.uklad</code>
     */
    public static final Uklad UKLAD = new Uklad();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UkladRecord> getRecordType() {
        return UkladRecord.class;
    }

    /**
     * The column <code>public.uklad.nazwa</code>.
     */
    public final TableField<UkladRecord, String> NAZWA = createField("nazwa", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>public.uklad.ilosc_planet</code>.
     */
    public final TableField<UkladRecord, Integer> ILOSC_PLANET = createField("ilosc_planet", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.uklad</code> table reference
     */
    public Uklad() {
        this("uklad", null);
    }

    /**
     * Create an aliased <code>public.uklad</code> table reference
     */
    public Uklad(String alias) {
        this(alias, UKLAD);
    }

    private Uklad(String alias, Table<UkladRecord> aliased) {
        this(alias, aliased, null);
    }

    private Uklad(String alias, Table<UkladRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Uklad as(String alias) {
        return new Uklad(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Uklad rename(String name) {
        return new Uklad(name, null);
    }
}
