/*
 * This file is generated by jOOQ.
*/
package Galaktyka2;


import Galaktyka2.tables.Planeta;
import Galaktyka2.tables.Uklad;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.planeta</code>.
     */
    public static final Planeta PLANETA = Galaktyka2.tables.Planeta.PLANETA;

    /**
     * The table <code>public.uklad</code>.
     */
    public static final Uklad UKLAD = Galaktyka2.tables.Uklad.UKLAD;
}
